using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DAL.Models
{
    public class ANAGDIP
    {
        public short ENTE { get; set; }
        public int PROGRESSIVO { get; set; }
        public int? MATRICOLA { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public short? SESSO { get; set; }
        public string CODFISC { get; set; }
        public float? LUOGONAS { get; set; }
        public DateTime? DATANAS { get; set; }
        public string INDIRIZZO { get; set; }
        public float? CAP { get; set; }
        public float? LUOGORES { get; set; }
        public string STATOCIVILE { get; set; }
        public string TITOLOSTUDIO { get; set; }
        public float? CODABI { get; set; }
        public float? CODCAB { get; set; }
        public string NUMCC { get; set; }
        public string DESACCRE { get; set; }
        public string POSIZIONE { get; set; }
        public string MANSIONE { get; set; }
        public string QUALIFICA { get; set; }
        public string SINDACATO { get; set; }
        public string POSINAIL { get; set; }
        public string ASSOGG { get; set; }
        public short? SOGGTFR { get; set; }
        public string LIVELLO { get; set; }
        public string IRPEF { get; set; }
        public float? PARTTIME1 { get; set; }
        public float? PARTTIME2 { get; set; }
        public short? TIPOPTIME { get; set; }
        public short? DETFIGLI { get; set; }
        public short? DETFAMIGLIARI { get; set; }
        public string DETCONIUGE { get; set; }
        public float? REDDCONIUGE { get; set; }
        public DateTime? DATADECCON { get; set; }
        public string DETLAVDIP { get; set; }
        public float? REDDLAVDIP { get; set; }
        public string DETULTERIORI { get; set; }
        public string CONDPART { get; set; }
        public float? IMPOFISCTS1 { get; set; }
        public float? IMPOFISCTS2 { get; set; }
        public float? ARIMPONANP { get; set; }
        public float? ARCALCANP { get; set; }
        public float? ARTRATANP { get; set; }
        public float? ARDATRANC { get; set; }
        public float? ARRATAMES { get; set; }
        public float? ACIMPONANP { get; set; }
        public float? ACCALCANP { get; set; }
        public float? ACTRATANP { get; set; }
        public float? ACDATRANC { get; set; }
        public float? ACRATAMES { get; set; }
        public float? RITSIND { get; set; }
        public float? RESFERIEAP { get; set; }
        public string TIPOFERIE { get; set; }
        public float? BANCAMONTEORE { get; set; }
        public float? BANCAOREFATTE { get; set; }
        public string UTENTE { get; set; }
        public DateTime? DATAMODIFICA { get; set; }
        public float? RECORELAVMESE { get; set; }
        public float? RECORECONTRATTO { get; set; }
        public float? RECOREMESE { get; set; }
        public float? RECOREMESPREC { get; set; }
        public string EMAILDIP { get; set; }
        public string TELDIP { get; set; }
        public string CELLDIP { get; set; }
        public string INDIRIZZOREC { get; set; }
        public float? CAPREC { get; set; }
        public float? LUOGOREC { get; set; }
        public short? TIPCONTFORM { get; set; }
        public short? APPDEDFISSA { get; set; }
        public short? APPDEDLAVDIP { get; set; }
        public float? SNORESID { get; set; }
        public float? SNOACCA { get; set; }
        public float? SNOREC { get; set; }
        public float? SNOPAG { get; set; }
        public float? SFERESID { get; set; }
        public float? SFEACCA { get; set; }
        public float? SFEREC { get; set; }
        public float? SFEPAG { get; set; }
        public float? SNTRESID { get; set; }
        public float? SNTACCA { get; set; }
        public float? SNTREC { get; set; }
        public float? SNTPAG { get; set; }
        public float? SFNRESID { get; set; }
        public float? SFNACCA { get; set; }
        public float? SFNREC { get; set; }
        public float? SFNPAG { get; set; }
        public string CODCIN { get; set; }
        public string CREDFIN { get; set; }
        public short? TIPOLOGIA { get; set; }
        public float? TFMLORDO { get; set; }
        public float? TFMDEDUZ { get; set; }
        public short? TFMANNI { get; set; }
        public short? TFMMESI { get; set; }
        public short? TFMGIORNI { get; set; }
        public DateTime? TFMSCAD { get; set; }
        public string RIFCONT { get; set; }
        public short? MODOREDDPRES { get; set; }
        public string EMTIPRAP { get; set; }
        public string EMCODATT { get; set; }
        public string EMALTRASS10 { get; set; }
        public string EMALTRASS15 { get; set; }
        public string TIPPAGSETIF { get; set; }
        public short? ANZANNI { get; set; }
        public short? ANZMESI { get; set; }
        public string CODIBAN { get; set; }
        public short? CODCTLBAN { get; set; }
        public short? EREDEDI { get; set; }
        public short? IRPEFSOSPESA { get; set; }
        public short? MATRINPS { get; set; }
        public short? TIPODETRAZ07 { get; set; }
        public float? ACIMPONANC { get; set; }
        public float? ACCALCANC { get; set; }
        public float? ACTRATANC { get; set; }
        public float? ACDATRANC2 { get; set; }
        public float? ACRATAMESANC { get; set; }
        public float? COMUNEANP { get; set; }
        public float? COMUNEANC { get; set; }
        public string CFCONIUGE { get; set; }
        public short? MESITERZICON { get; set; }
        public string SINDACATO2 { get; set; }
        public string SINDACATO3 { get; set; }
        public float? RITSIND2 { get; set; }
        public float? RITSIND3 { get; set; }
        public short? WEBACCESS { get; set; }
        public string WEBUSER { get; set; }
        public string WEBPASSWORD { get; set; }
        public string MAGG1 { get; set; }
        public string MAGG2 { get; set; }
        public string MAGG3 { get; set; }
        public string MAGG4 { get; set; }
        public string WEBPASSWORDTMP { get; set; }
        public short? FLAG93000 { get; set; }
        public short? PERSEO { get; set; }
        public float? ALIPERSEO { get; set; }
        public DateTime? DATAPERSEO { get; set; }
        public short? OPTANTETFR { get; set; }
        public short? CONTRSOLID { get; set; }
        public string COGNOMECON { get; set; }
        public string NOMECON { get; set; }
        public DateTime? DATANASCON { get; set; }
        public float? LUOGONASCON { get; set; }
        public short? TIPOASSIMILATO { get; set; }
        public short? FAMHANDY { get; set; }
        public short? BONUSRENZI { get; set; }
        public string CODVOLONTARIO { get; set; }
        public string CODSWIFT { get; set; }
        public string CODPAGAMENTO { get; set; }
        public string UTENTELDAP { get; set; }
        public string NOTE { get; set; }
        public float? EXCOMUNE { get; set; }
        public short? LOCKRITSIND1 { get; set; }
        public short? LOCKRITSIND2 { get; set; }
        public short? LOCKRITSIND3 { get; set; }
        public string COGNOMENOME { get; set; }
        public string NOTEFISSE { get; set; }
        public short? TRATTINTEG { get; set; }
        public short? TIRESTRATE { get; set; }
        public short? ULTDETRAZ { get; set; }
        public short? UDRESTRATE { get; set; }
        public short? UNITAOPERATIVA { get; set; }
        public int? ORE35 { get; set; }
        public short? MODOTFRDITTA { get; set; }
        public float? IMPORTOTFRDITTA { get; set; }
        public int? SIMULATODI { get; set; }
        public int? DECONTRIBUZIONE { get; set; }
        public short? ACESENZIONE { get; set; }
        public short? SILENZIOASSENSO { get; set; }
        public string TIPOLAVUNIEMENS { get; set; }
        public DateTime? DATA_MOBILITA { get; set; }
        public short? FIGLINODET { get; set; }
        public float? UTIMPORTO { get; set; }
        public float? UTRATA { get; set; }
        public float? UTTRATTENUTO { get; set; }
        public float? CEDOLARESECCA { get; set; }
        public short? ISRESTRATE { get; set; }
        public short? INDSOSTEGNO { get; set; }
        public short? OLDDECONT { get; set; }

        public virtual ICollection<DOCUMENTO_UPLOAD_DIPENDENTE> DOCUMENTO_UPLOAD_DIPENDENTEs { get; set; } = new List<DOCUMENTO_UPLOAD_DIPENDENTE>();
    }
}
